### PR TITLE
Fix QT5 crash

### PR DESCRIPTION
**Pull request by krzeminskim**
Fix crashes on QT5.

### CODE REVIEW

**Comment by bovirus** [comment]
@krzeminskim

Thanks for the fix.

Do you have a good experience on QT projects?
Then it could be help me about how to load more language file in QT projects.

**Comment by krzeminskim** [comment]
Do you have exact scenario for the QT4 break?
I try run it on Ubuntu and QT4. All screens that have been fixed on QT5 works also on QT4.

**Comment by cedricp** [comment]
I fixed the problem after the merge, just look here : 
https://github.com/cedricp/ddt4all/commit/0afa5fc310f1af85bd785efa2da3380268ebeaf5#diff-ec855f0077cde24ba5bd553c5aeb5f15L777

**Comment by krzeminskim** [comment]
Okay, I was suspecting that this will be file open issue, however I do not understand why it is working for me on QT4 and ubuntu. Will try to dig it out thou.
Thanks for fixing!

**Pull request merged**
