### PR TITLE
Port to Qt5

### PR DESCRIPTION
**Pull request by mrtati**
Hi Cedric,
your software is amazing and thanks for doing it!

However, I could not run it on latest Ubuntu 17.10 due to missing parts in Qt4, namely the webkit part.
Trying to hack an earlier Ubuntu version to docker was not successful either and I did not want to create a VM only for this tool, so I decided to quickly port it to Qt5 if possible. This is my first attempt to work with Qt at all. It seems to work as the GUI loads and you can click around. I could not try it yet on a real car as I have only an old ELM327 v1.0a at hands.

Please consider to merge.
Some more testing might be needed as I have not tried it on Windows.

Br, Attila

### CODE REVIEW

**Comment by cedricp** [comment]
Thank you for that, I'm gonna create a **QT5** branch in my repo and will merge to **master** when stable

**Comment by cedricp** [comment]
I created a **qt5** branch that should supports both **qt4** and **qt5**, could you try it and report ?

**Comment by mrtati** [comment]
Hi,
I pulled the qt5 branch and did experiment a little with it. There seems to be a generic problem.
When starting in simulation and then double clicking on any ECU name entry, then it throws the following exception:
```
Traceback (most recent call last):
  File "ddt4all.py", line 194, in ecuSel
    selected = utf8(item[0].toString())
AttributeError: 'unicode' object has no attribute 'toString'
```
I think this is due to that Qt5 gives back the results as unicode already.

Also, when I hit the scan in simulated mode, so that I have some ECUs already listed in the box below the ECU name list and I click on any ECU that were found by simulation, the same problem happens, but on a different place in code.
```
Traceback (most recent call last):
  File "ddt4all.py", line 797, in changeECU
    ecu_name = utf8(item[0].toString())
AttributeError: 'unicode' object has no attribute 'toString'
```
I am using
`Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2`
on Ubuntu 17.10 (Artful Aardvark)
and 
`Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.2.0) on "xcb" `

Br, Attila

**Comment by cedricp** [comment]
Should be OK now, just fixed it

**Comment by heyb4r** [comment]
Hi Cedric,
great news to see that QT5 is now supported 
here is a small patch in order ddt4all to work under Mac OS after installing pyqt using homebrew
[patch.txt](https://github.com/cedricp/ddt4all/files/1600300/patch.txt)
hope this help
best regards

**Comment by cedricp** [comment]
Thank you for the patch, I added it, could you try it to check if it works ?

**Comment by heyb4r** [comment]
there is a mistake on line 13 
please replace line 13 with :  import PyQt5.QtWidgets as widgets
Regards

**Comment by cedricp** [comment]
Done, thank you :+1:

**Comment by heyb4r** [comment]
It's OK 
thx

**Comment by mrtati** [comment]
Hi Cedric,

I tried latest version and it works well on Ubuntu.
Thanks!

Br, Attila

**Comment by cedricp** [comment]
Great, I'll check that everything works with **Qt4** and I'll merge it to master.
Thank you guys !

**Pull request closed without merging**
